# Generated by Django 4.1.2 on 2023-02-11 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0002_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delivery', models.BooleanField(verbose_name='Is Delivery')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total price')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.BigIntegerField(blank=True, null=True, verbose_name='Phone')),
                ('country', models.CharField(blank=True, max_length=64, null=True, verbose_name='Country')),
                ('city', models.CharField(blank=True, max_length=24, null=True, verbose_name='City')),
                ('street', models.CharField(blank=True, max_length=128, null=True, verbose_name='Street')),
                ('item', models.ManyToManyField(related_name='purchase', to='shop.item', verbose_name='Item')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
